services:
  postgres:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketly
    volumes:
      - './data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - "6379:6379"